All events overview (Browse HomePage)
swent-sp-2024-event-radar/event-radar-app pull request #122
Opened 2024-04-16 21:23 UTC by wisdomseeker2001

Hi, this is fairly simple to understand when you look at code.

Decided to show following in the list:
Photo, Name, Date 

if you objections, lets talk about it,  all event apps usually have:
Photo, Name, Date  + Location as preview 

I suggest we keep it simple, description should only be relevant once someone clicks on it and reads more, but first they should see the date to see if they can make it, especially if we are gonna sort the vents by date by default (to be discussed)

2024-04-17 13:03 UTC, Nath-Assa commented on app/src/main/java/com/github/se/eventradar/model/event/AllEventOverview.kt
Fix Line 31, should be: _uiState.value = _uiState.value + eventListView

2024-04-17 21:35 UTC, jgeaso1266 requested changes
A few suggestions and name change ideas.

2024-04-17 21:35 UTC, jgeaso1266 commented on app/src/main/java/com/github/se/eventradar/model/event/AllEventOverview.kt
> +class AllEventOverview(private val db: FirebaseFirestore = Firebase.firestore): ViewModel() {
This is not a good name. What is "all events"? `ViewModel` should be in the name.

2024-04-17 21:35 UTC, jgeaso1266 commented on app/src/main/java/com/github/se/eventradar/model/event/AllEventOverview.kt
> +                db.collection("EVENT")
nit: `event` should be lowercase.

2024-04-17 21:35 UTC, jgeaso1266 commented on app/src/main/java/com/github/se/eventradar/model/event/AllEventOverview.kt
> +                            _uiState.value + eventListView
What is this line doing? I think this is the line Nathaniel said is wrong.

2024-04-17 21:35 UTC, jgeaso1266 commented on app/src/main/java/com/github/se/eventradar/model/event/Event.kt
> +    val contact: String,
suggestion: I think this should be a reference to the uid of the Host, not just a contact email string.

2024-04-17 21:35 UTC, jgeaso1266 commented on app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
> +fun HomeScreen() { // viewModel: EventViewModel = viewModel() + Navigation
Has this been synced with main? There should be a navigation actions and view model in the parameters.

2024-04-17 21:35 UTC, jgeaso1266 commented on app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
> +                    text = event.eventName,
nit: `name` would be a better variable name for this.

2024-04-18 06:35 UTC, christinehahaa commented
This PR request has been closed and replaced with PR request #125 for the following reasons:
- ViewModel UI state was modified to allow more flexibility for getting a singular event, a list of filtered events, or a list of all events
- ViewModel extracts more data, which can be used for other functionalities
- It is the UI that chooses what is/isn't displayed.
   - Joyti's comments regarding what is displayed in the list is still relevant, but should be noted for the devop of the UI.

2024-04-18 06:35 UTC, closed without merging